### ISSUE TITLE
Enhancement: mark some location with location icon on the map 

### ISSUE THREAD

**Issue by ctang0416** [info442-spr22/f-team#85] opened 2022-05-19 05:41 UTC
For the map page now, we can search some locations. But I think sometimes people don't really know why elementary school they should search for. I think it would be good to show some locations even before people start to search. This can give people more ideas about what they should search or they can just click on the location that's already shown to them.

**Comment by cmarq07** [comment] 2022-05-23 16:11
Duplicate of #59

**Closed by cmarq07** 2022-05-23 16:11 UTC
Labels: duplicate
