### ISSUE TITLE
[Minor Bug] Nothing Happens After Submitting Form

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/f-team#70] opened 2022-05-18 16:23 UTC
After filling out the food resource form correctly with no error messages, pressing the submit button does not do anything when I assume it should at least clear the form results or take the person to a new pag. (encountered on chrome Version 101.0.4951.64). It would be helpful if there was a pop-up message so the user can know that their information has been submitted.

**Comment by Jaehoon01** [comment] 2022-05-23 16:02
Duplicate of 71 & 78.

**Comment by cmarq07** [comment] 2022-05-23 16:49
Not a bug, works on the backend just nothing is displayed to the user upon form submission

**Closed** 2022-05-29 21:07 UTC
Labels: bug, enhancement
