### ISSUE TITLE
(Major Bug) Unable to search for any elementary schools

### ISSUE THREAD

**Issue by spudists** [info442-spr22/f-team#61] opened 2022-05-18 16:18 UTC
When trying to use the primary map feature, I cannot get any results to show regardless of what I have searched.  Possibly the field is looking for an exact match that I have not entered, but from a user perspective there should be some options available to choose from initially or it should accept/autofill close names.
Chrome, HP Pavilion
Go to the map page and try to search any elementary name or generic name such as 'Seattle' or "Laurelhurst"
No results are returned

**Comment by cmarq07** [comment] 2022-05-23 16:09
Duplicate of #56

**Closed by cmarq07** 2022-05-23 16:09 UTC

**Comment by cherimarie** [comment] 2022-06-08 15:08
For issue triaging, this is a dupe of #56, but for phase 7 grading purposes, it's distinct so will get full points.
